# Generated by Django 5.1.4 on 2025-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_partner_options_alter_partner_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
