# Generated by Django 5.1.4 on 2025-01-03 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_alter_partner_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="partners.partner",
            ),
        ),
    ]
