# Generated by Django 5.1.4 on 2025-01-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0004_remove_transaction_scanned_at_transaction_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
