# Generated by Django 5.1.4 on 2025-01-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_address_alter_customer_groups_and_more"),
        ("transactions", "0005_alter_transaction_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcodescanlog",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="barcode_logs",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="customers.customer",
            ),
        ),
    ]
