# Generated by Django 5.1.4 on 2025-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
