# Generated by Django 5.1.4 on 2025-01-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("customers", "0002_customer_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customer_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="customer_user_permissions",
                to="auth.permission",
            ),
        ),
    ]
