version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-+ni3lezx!@z##6w(3$yc-v8%9h7zug9ev=7pvr*yyl9071(j41
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DB_NAME=loyalty_app_db
      - DB_USER=loyalty_user
      - DB_PASSWORD=loyalty
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:14
    container_name: loyalty_db
    restart: always
    environment:
      POSTGRES_USER: loyalty_user
      POSTGRES_PASSWORD: monkey
      POSTGRES_DB: loyalty_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
